services:
  app:
    build:
      context: ./app
    container_name: app
    ports:
      - "3000:3000"
    volumes:
      - ./app:/usr/src/app:rw
      - /usr/src/app/node_modules
    depends_on:
      - server
    environment:
      - REACT_APP_SERVER_URL=http://server:4000
  server:
    build:
      context: ./server
    container_name: server
    ports:
      - "4000:4000"
    volumes:
      - ./server:/usr/src/server:rw
      - /usr/src/server/node_modules
    depends_on:
      - db
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=cooper-films
      - DATABASE_URL=postgres://postgres:postgres@db:5432/cooper-films?schema=public
  db:
    image: postgres:14
    container_name: database
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cooper-films
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:

