export enum ScriptStatus {
  AWAITING_ANALYSIS = 'AWAITING_ANALYSIS',
  IN_ANALYSIS = 'IN_ANALYSIS',
  AWAITING_REVIEW = 'AWAITING_REVIEW',
  IN_REVIEW = 'IN_REVIEW',
  AWAITING_APPROVAL = 'AWAITING_APPROVAL',
  VOTED = 'VOTED',
  IN_APPROVAL = 'IN_APPROVAL',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  ERROR = 'ERROR',
}
